# Site settings
title: Steven Lu
email: tacticalazn@gmail.com
description: "software engineer and health fanatic"
baseurl: ""
url: "http://stevenlu.com"
twitter_username: stevenlu
github_username:  sjlu

# Build settings
markdown: kramdown
permalink: pretty
