# Site settings
title: Steven Lu
email: tacticalazn@gmail.com
description: "software engineer & health fanatic"
baseurl: ""
url: "http://stevenlu.com"
twitter_username: stevenlu
github_username:  sjlu

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
encoding: "UTF-8"
sass:
  style: :compressed

# Nav
navigation:
  - title: Posts
    url: /posts
  - title: Projects
    url: /projects